### ISSUE TITLE
Tweaks for those migrating from Ritwick's extension

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#159]
Although these are my current plans, this is still **Open For Discussion** and comments are welcome (for thoughts) and 👍 for those in support

----

@ritwickdey has kindly archived his extension and is redirecting people to my fork here. Now more people will be migrating I want to try and make the process easier.

The key points are:
- Add `liveSassCompile.settings.showOutputWindow` as a deprecated fallback
    When a `liveSassCompile.settings.showOutputWindowOn` setting is not present I will check for a `true` or `false` value of `liveSassCompile.settings.showOutputWindowOn`
    - When `true` I will use the `Information` setting
    - When `false` I will use the `Warning` setting (which will only output on errors or warnings)
    - This option will be marked as deprecated with a note to use the new setting. However, it will likely never be removed as people could be migrating in the next major release (and beyond)
- The `autoprefix` setting needs to accept `null` and will act like it's `false`

----

## Tasks

- [x] Allow fallback to `showOutputWindow` when `showOutputWindowOn` isn't present
- [x] Allow `null` in `autoprefix` setting
- [x] Update documentation to note these changes

**Comment by glenn2223** [comment]
I have code changes ready to go, just waiting a day or two before applying in case anyone has feedback

**Comment by glenn2223** [comment]
No objections so I'm pushing these two tweaks
