### ISSUE TITLE
Switching up the watching pattern and filesystem implementation

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#325]
### Issues

1. Using VS Code's onDidChange event isn't enough to identify external changes (like those from the dev tools). 
2. `fdir` is a fantastic tool, but there have been a few issues with shadow files and network drives/files

### Proposal

Rather than using VS Code's onDidChange event, we will instead implement their file watcher

We will move away `fdir` and use VS Code's fs manager

### TODO

- [ ] Move to VS Code's own fs manager
- [ ] Remove the dependency on `fdir`
- [ ] Move to file watching rather than `onDidChange` event
