### ISSUE TITLE
Language Server 

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#326]
### Issues

Currently, there is no way of knowing that your SASS is invalid until you save. Other tools update the UI and highlight issues

### Proposal

Create a language server utility which is called by the `onDidChangeTextDocument` event. But, we only catch errors out not compile anything

### TODO

- [ ] Research the language server best implementation
- [ ] See if we can output all errors and not just stop at the first (like it does with compilation)
- [ ] Ensure the method is called on the `onDidChangeTextDocument` event
- [ ] Ensure the UI is updated with the red error wiggly underscores
