### ISSUE TITLE
Switch to `sass-embedded`

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#327]
### Issues

The standard SASS package, combined with some VS Code weirdness, means I have to specify that I want the NodeJS version of the package.

### Proposal

OLD: ~Use the `compileString` method with my own Importer utilising the built-in fs module.~ 

NEW: Fix this issue and also use the speedier compiler

This has the added benefit of:
-   prepping for #328 
-   using the speedier **Embedded Sass Host** along with its' async methods

### TODO

- [ ] Move to the embedded SASS host
- [X] ~Move to `compileStringAsync`~ Not immediately required
  - [X] ~Implement the Importer~ N/A
- [ ] Possibly remove some deprecated settings (if they aren't supported) like `formats[].lineFeed`
- [ ] Update docs

#### Related issues

- #328
