### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#328]
### Issue

VS Code has the web environment [vcode.dev](https://vscode.dev). However, this extension doesn't currently support it due to the underlying dependencies on node modules like fs, path, utils, etc.

### Proposal

Add browser support. I hope this doesn't take too much work by switched to `sass-embedded`

### TODO

- [ ] Check if there are extra requirements
- [ ] Stop using native "node" modules/references (like path and fs)
- [ ] Switch from `sass-embedded.compileAsync` to `sass-embedded.compileStringAsync`
- [ ] Add the new `browser` location to the `package.json`
- [ ] Update readme and docs

### Depends on

- #327
