### ISSUE TITLE
Do partials correctly

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#329]
### Issue

Currently, saving a partial file compiles all non-partial files. This means that many files are potentially being compiled for no reason.

### Proposal

Working on a typescript compiler has allowed me to come up with a method that correctly identifies linked files. By identifying the link I will know the saved file is a "child" and to only compile its "parent" files

### TODO

- [ ] Implement the new method
- [ ] Use the save event to update the records
- [ ] Save the records to keep load times short
- [ ] Change the start-up method to:
  - [ ] check for changes if the data exists
  - [ ] create the data if it doesn't exist
- [ ] Update readme and docs

### Should resolve/close

- #17 
- #185

**Comment by xiaomilao** [comment]
I would like to know if this issue has been resolved: Whenever I save an SCSS file that starts with an underscore, all SCSS files in the workspace get compiled. Below is my configuration:
```
{
    "liveSassCompile.settings.exclude": [
      "node_modules/**",
      ".vscode/**",
    ],
    "liveSassCompile.settings.formats": [
      {
        "format": "compressed", 
        "extensionName": ".css", 
        "savePath": "~/../css" 
      }
    ],
    "liveSassCompile.settings.generateMap": false,
    "liveSassCompile.settings.compileOnWatch": false,    
}
```

**Comment by glenn2223** [comment]
The short of it is no, sorry. Got 2 uni modules, work and kids, so this has been slipping the net a little. I plan to pick up activity on the project again soon

The default configuration is obviously not working for you. You need to utilise the partialsList setting to specify the pattern for all your partial files. The default is `/**/_*.s[ca]ss`which is the way SASS recommend partials are formatted and it's why all files that start with an underscore trigger compilation of all files
