### ISSUE TITLE
FEATURE: Compilation "killer"

### ISSUE THREAD

**Issue by glenn2223** [glenn2223/vscode-live-sass-compiler#333]
### Issues

Compilation can get stuck if the user has managed to get into an infinite loop. We need to be able to kill the compilation process.

### Proposal

VS Code allows a "progress" pop-up that has a cancellation feature. I will investigate this and see if it's suitable to use. To save "flashes" from quick compilations, I may make it show only after 2/3 seconds of compilation

### TODO

- [ ] Investigate method is suitable
- [ ] Implement the cancellation method
- [ ] Update docs with a reference to the "feature"

#### Related issues

- #332
